apiVersion: apps/v1
kind: Deployment
metadata:
  name: <YOUR_MS_NAME>-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <YOUR_MS_NAME>
  template:
    metadata:
      labels:
        app: <YOUR_MS_NAME>
    spec:
      containers:
        - name: <YOUR_MS_NAME>-ms
#          You need to create the repository in AWS ECR first
          image: 881619806726.dkr.ecr.us-east-2.amazonaws.com/<YOUR_MS_NAME>/<YOUR_MS_NAME>-ms:latest
          imagePullPolicy: allways
          ports:
            - containerPort: 80
              protocol: TCP
          env:
      imagePullSecrets:
        - name: regcred