apiVersion: v1
kind: Service
metadata:
  name: serviceRegisterMS-service
spec:
  type: ClusterIP
  selector:
    app: serviceRegisterMS
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80