AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Service responsible of generate post sales recommendations
Globals:
  Function:
    Timeout: 30
Resources:
  updateRecomendations:
    Type: AWS::Serverless::Function
    FunctionName: update-recommendations
    Properties:
      CodeUri: .
      Handler: src/app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
      Events:
        orders-topic:
          Type: SNS
          Properties:
            Topic:
              Ref: arn:aws:sns:us-west-2:881619806726:technical-orders-topic
