AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Service responsible of manage warranties
Globals:
  Function:
    Timeout: 30
Resources:
  listenTechOrders:
    Type: AWS::Serverless::Function
    FunctionName: listenTechOrders
    Properties:
      CodeUri: .
      Handler: src/listenTechOrders.lambdaHandler
      Runtime: nodejs12.x
      Events:
        MySQSEvent:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-west-2:881619806726:technical-orders-topic
  getWarrantiesByPlate:
    Type: AWS::Serverless::Function
    FunctionName: get-warranties-by-plate
    Properties:
      CodeUri: .
      Handler: src/getWarrantiesByPlate.lambdaHandler
      Runtime: nodejs12.x