AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Service responsible of manage the orquestration
Globals:
  Function:
    Timeout: 30
Resources:
  OrquestratorFunction:
    Type: AWS::Serverless::Function
    FunctionName: orquestrator
    Properties:
      CodeUri: src
      Handler: orquestrator
      Runtime: go1.x
      Events:
        revisionFormatCommandQueue:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-west-2:881619806726:process-tech-revision-format-command.fifo