AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Service responsible of manage service centers
Globals:
  Function:
    Timeout: 30
Resources:
  getServiceCenterByName:
    Type: AWS::Serverless::Function
    FunctionName: get-service-center-by-name
    Properties:
      CodeUri: .
      Handler: src/getServiceCenterByNameCommand.lambdaHandler
      Runtime: nodejs12.x
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-west-2:881619806726:assign-service-center-command.fifo
  serviceCenterApi:
    Type: AWS::Serverless::Function
    FunctionName: service-center-api
    Properties:
      CodeUri: .
      Handler: src/serviceCenterApi.lambdaHandler
      Runtime: nodejs12.x