AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Service responsible of manage service centers
Globals:
  Function:
    Timeout: 30
Resources:
  saveServiceCenter:
    Type: AWS::Serverless::Function
    FunctionName: save-service-center
    Properties:
      CodeUri: .
      Handler: src/saveServiceCenter.lambdaHandler
      Runtime: nodejs12.x
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-west-2:881619806726:save-tech-order-command.fifo
  getServiceCenterByName:
    Type: AWS::Serverless::Function
    FunctionName: get-service-center-by-name
    Properties:
      CodeUri: .
      Handler: src/getServiceCenterByName.lambdaHandler
      Runtime: nodejs12.x