name: 'Serverless'

on:
  push:
    branches:
      - main
    paths:
      - 'serverless/**'

jobs:
  deploy-lambdas:
    name: 'Deploy Lambdas'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./serverles

    steps:
      - name: Checkout
        uses: actions/checkout@v2